const data = [
  {
    id: 1,
    firstName: "Lenox",
    lastName: "Lutfi",
    title: "QA Engineer",
    company: "Contour",
    phoneNumber: "123-456-7890",
    website: "https://contour.network",
    email: "lenox.lutfi@contour.network",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Doe",
    title: "FE Developer",
    company: "Contour",
    phoneNumber: "123-456-7890",
    website: "https://contour.network",
    email: "jane.doe@contour.network",
  },
  {
    id: 3,
    firstName: "Leo",
    lastName: "Smith",
    title: "Designer",
    company: "Contour",
    phoneNumber: "123-456-7890",
    website: "https://contour.network",
    email: "Leo.Smith@contour.network",
  },
  {
    id: 4,
    firstName: "Levi",
    lastName: "Hughes",
    title: "BE Developer",
    company: "Contour",
    phoneNumber: "123-456-7890",
    website: "https://contour.network",
    email: "Levi.Hughes@contour.network",
  },
];
export default data;
